name = "Hugo Minimalist"
license = "BSD-3-clause"
licenselink = "https://github.com/ZekeriyaAY/hugo-minimalist/blob/main/LICENSE"
description = "A minimalist personal theme for Hugo."
homepage = "https://github.com/ZekeriyaAY/hugo-minimalist"
tags = ["blog", "clean", "minimal", "personal", "responsive", "resume", "simple"]
features = ["responsive", "simple"]
min_version = "0.80.0"

[author]
  name = "Zekeriya AY"
  homepage = "https://zekeriyaay.com"

[original]
  name = "hugo-minimalist"
  homepage = "https://aniolmarti.cat"
  repo = "https://github.com/aniolm9/hugo-minimalist"
